import PDFDocument from "pdfkit";

export type PdfDoc = InstanceType<typeof PDFDocument>;

export function drawSampleWatermarkOnCurrentPage(doc: PdfDoc): void {
  const w = doc.page.width;
  const h = doc.page.height;
  doc.save();
  // Top banner
  doc.rect(0, 0, w, 22).fillColor("#fef3c7").fill();
  doc.fontSize(9).fillColor("#92400e").text(
    "SAMPLE — NOT A REAL CLIENT DOCUMENT.  Generated by Hubify PDF Mockup Gallery.",
    0, 7, { width: w, align: "center", lineBreak: false }
  );
  // Diagonal SAMPLE stamp
  doc.rotate(-30, { origin: [w / 2, h / 2] });
  doc.fillOpacity(0.18);
  doc.fontSize(110).fillColor("#9ca3af")
    .text("SAMPLE", 0, h / 2 - 60, { width: w, align: "center", lineBreak: false });
  doc.fillOpacity(1);
  doc.restore();
}

export function applyWatermarkToAllPages(doc: PdfDoc): void {
  const range = (doc as unknown as { bufferedPageRange: () => { start: number; count: number } })
    .bufferedPageRange();
  for (let i = range.start; i < range.start + range.count; i++) {
    doc.switchToPage(i);
    drawSampleWatermarkOnCurrentPage(doc);
  }
}

export function streamPdf(build: (doc: PdfDoc) => void): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: "LETTER", bufferPages: true });
    const chunks: Buffer[] = [];
    doc.on("data", (c: Buffer) => chunks.push(c));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);
    // Reserve room for the SAMPLE banner on the first page.
    doc.y = 32;
    try {
      build(doc);
    } catch (e) {
      reject(e);
      return;
    }
    applyWatermarkToAllPages(doc);
    doc.end();
  });
}

export function hr(doc: PdfDoc, color: string = "#e2e8f0"): void {
  doc.moveTo(50, doc.y).lineTo(doc.page.width - 50, doc.y).strokeColor(color).stroke();
  doc.moveDown(0.4);
}

export function sectionTitle(doc: PdfDoc, label: string, color: string = "#1e40af"): void {
  doc.moveDown(0.4);
  doc.fontSize(12).fillColor(color).text(label.toUpperCase(), 50, doc.y, { characterSpacing: 1 });
  doc.moveDown(0.2);
  hr(doc);
}

export function kv(doc: PdfDoc, label: string, value: string, x: number, y: number, w: number): void {
  doc.fontSize(7).fillColor("#64748b").text(label.toUpperCase(), x, y, { width: w, characterSpacing: 0.6 });
  doc.fontSize(10).fillColor("#0f172a").text(value || "—", x, y + 11, { width: w });
}
