import PDFDocument from "pdfkit";

export type PdfDoc = InstanceType<typeof PDFDocument>;

export function addSampleWatermark(doc: PdfDoc) {
  const w = doc.page.width;
  const h = doc.page.height;
  doc.save();
  doc.rotate(-30, { origin: [w / 2, h / 2] });
  doc.fontSize(110)
    .fillColor("#9ca3af", 0.18 as any)
    .text("SAMPLE", 0, h / 2 - 60, { width: w, align: "center" });
  doc.restore();
  doc.fillColor("black", 1 as any);
}

export function addSampleBanner(doc: PdfDoc) {
  doc.save();
  doc.rect(0, 0, doc.page.width, 22).fillColor("#fef3c7").fill();
  doc.fontSize(9).fillColor("#92400e").text(
    "SAMPLE — NOT A REAL CLIENT DOCUMENT.  Generated by Hubify PDF Mockup Gallery.",
    0, 7, { width: doc.page.width, align: "center" }
  );
  doc.restore();
  doc.fillColor("black", 1 as any);
  doc.y = 32;
}

export function attachWatermark(doc: PdfDoc) {
  // Apply to current page
  addSampleBanner(doc);
  addSampleWatermark(doc);
  // Apply to every subsequent page
  doc.on("pageAdded", () => {
    addSampleBanner(doc);
    addSampleWatermark(doc);
  });
}

export function streamPdf(build: (doc: PdfDoc) => void): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: "LETTER" });
    const chunks: Buffer[] = [];
    doc.on("data", (c: Buffer) => chunks.push(c));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);
    attachWatermark(doc);
    try {
      build(doc);
    } catch (e) {
      reject(e);
      return;
    }
    doc.end();
  });
}

export function hr(doc: PdfDoc, color = "#e2e8f0") {
  doc.moveTo(50, doc.y).lineTo(doc.page.width - 50, doc.y).strokeColor(color).stroke();
  doc.moveDown(0.4);
}

export function sectionTitle(doc: PdfDoc, label: string, color = "#1e40af") {
  doc.moveDown(0.4);
  doc.fontSize(12).fillColor(color).text(label.toUpperCase(), 50, doc.y, { characterSpacing: 1 });
  doc.moveDown(0.2);
  hr(doc);
}

export function kv(doc: PdfDoc, label: string, value: string, x: number, y: number, w: number) {
  doc.fontSize(7).fillColor("#64748b").text(label.toUpperCase(), x, y, { width: w, characterSpacing: 0.6 });
  doc.fontSize(10).fillColor("#0f172a").text(value || "—", x, y + 11, { width: w });
}
