import { streamPdf, sectionTitle, kv, hr, type PdfDoc } from "./index";
import { getSamplePropertyReport, type SamplePropertyReport } from "../pdfMockData";
import { getHubifyHomesLogoBuffer } from "../brandAsset";

export function generateSamplePropertyReportPdf(
  data: SamplePropertyReport = getSamplePropertyReport()
): Promise<Buffer> {
  return streamPdf((doc) => renderPropertyReport(doc, data));
}

function renderPropertyReport(doc: PdfDoc, d: SamplePropertyReport): void {
  const W = doc.page.width;
  const M = 50;

  doc.rect(0, 32, W, 70).fillColor("#7c3aed").fill();
  doc.fontSize(20).fillColor("#ffffff").text("Property Report", M, 52);
  doc.fontSize(10).fillColor("#ede9fe").text(d.property.address, M, 80);
  const hubifyLogo = getHubifyHomesLogoBuffer();
  if (hubifyLogo) {
    const logoBoxW = 110, logoBoxH = 40;
    const logoX = W - M - logoBoxW;
    const logoY = 47;
    doc.rect(logoX, logoY, logoBoxW, logoBoxH).fillColor("#ffffff").fill();
    try {
      doc.image(hubifyLogo, logoX + 6, logoY + 4, { fit: [logoBoxW - 12, logoBoxH - 8], align: "center", valign: "center" });
    } catch (err) {
      console.error("Failed to render Hubify Homes logo on sample property report PDF:", err);
    }
  }

  doc.fillColor("black");
  doc.y = 120;

  sectionTitle(doc, "Property Details");
  const y0 = doc.y;
  kv(doc, "Property #", d.property.number, M, y0, 110);
  kv(doc, "Type", d.property.type, M + 120, y0, 140);
  kv(doc, "Tier", d.property.tier, M + 270, y0, 100);
  kv(doc, "Status", d.property.status, M + 380, y0, 100);
  const y1 = y0 + 36;
  kv(doc, "Bed / Bath", d.property.bedBath, M, y1, 110);
  kv(doc, "Sq Ft", d.property.sqft, M + 120, y1, 110);
  kv(doc, "Year Built", d.property.yearBuilt, M + 240, y1, 110);
  kv(doc, "Pool / Spa", d.property.poolSpa, M + 360, y1, 120);
  doc.y = y1 + 36;

  sectionTitle(doc, "Contacts");
  const cy = doc.y;
  kv(doc, "Owner", d.contacts.owner, M, cy, W - M * 2);
  kv(doc, "Property Manager", d.contacts.manager, M, cy + 30, W - M * 2);
  kv(doc, "Emergency Contact", d.contacts.emergency, M, cy + 60, W - M * 2);
  doc.y = cy + 90;

  sectionTitle(doc, "Access & Security");
  const ay = doc.y;
  kv(doc, "Front Gate Code", d.access.gateCode, M, ay, 110);
  kv(doc, "Garage Code", d.access.garageCode, M + 120, ay, 110);
  kv(doc, "Alarm Code", d.access.alarm, M + 240, ay, 200);
  kv(doc, "Lockbox", d.access.lockbox, M, ay + 36, W - M * 2);
  doc.y = ay + 70;

  sectionTitle(doc, "Preferred Vendors");
  const vh = doc.y;
  doc.rect(M, vh, W - M * 2, 20).fillColor("#f5f3ff").fill();
  doc.fontSize(9).fillColor("#5b21b6");
  doc.text("Vendor", M + 8, vh + 6, { width: 180 });
  doc.text("Service", M + 200, vh + 6, { width: 130 });
  doc.text("Contact", M + 340, vh + 6, { width: 120 });
  doc.text("Rating", W - M - 50, vh + 6, { width: 42, align: "right" });
  doc.y = vh + 24;
  doc.fontSize(9).fillColor("#0f172a");
  for (const v of d.vendors) {
    const y = doc.y;
    doc.text(v.name, M + 8, y, { width: 180 });
    doc.text(v.service, M + 200, y, { width: 130 });
    doc.text(v.contact, M + 340, y, { width: 120 });
    doc.fillColor("#ca8a04").text(v.rating, W - M - 50, y, { width: 42, align: "right" });
    doc.fillColor("#0f172a");
    doc.y = y + 14;
    doc.moveTo(M, doc.y).lineTo(W - M, doc.y).strokeColor("#f1f5f9").stroke();
    doc.moveDown(0.15);
  }

  sectionTitle(doc, "Recent Tasks (last 30 days)");
  for (const t of d.recentTasks) {
    const y = doc.y;
    doc.fontSize(9).fillColor("#64748b").text(t.date, M, y, { width: 60 });
    doc.fillColor("#0f172a").text(t.title, M + 70, y, { width: 320 });
    doc.fillColor("#16a34a").text(t.status, W - M - 80, y, { width: 80, align: "right" });
    doc.y = y + 14;
  }

  doc.moveDown(0.4);
  sectionTitle(doc, "Upcoming Inspections");
  for (const u of d.upcomingInspections) {
    const y = doc.y;
    doc.fontSize(9).fillColor("#7c3aed").text(u.date, M, y, { width: 100 });
    doc.fillColor("#0f172a").text(u.title, M + 110, y, { width: 280 });
    doc.fillColor("#475569").text(u.assignee, W - M - 120, y, { width: 120, align: "right" });
    doc.y = y + 14;
  }

  doc.moveDown(0.6);
  hr(doc);
  doc.fontSize(8).fillColor("#94a3b8").text(
    "Property report generated by Hubify. For the complete record including photos, warranties, purchasing links, and notes, view this property in the Hubify Console."
  );
}
