import { streamPdf, sectionTitle, kv, hr } from "./index";

export function generateSamplePropertyReportPdf(): Promise<Buffer> {
  return streamPdf((doc) => {
    const W = doc.page.width;
    const M = 50;

    doc.rect(0, 32, W, 70).fillColor("#7c3aed").fill();
    doc.fontSize(20).fillColor("#ffffff").text("Property Report", M, 52);
    doc.fontSize(10).fillColor("#ede9fe").text("789 Beachfront Dr · Marco Island, FL 34145", M, 80);

    doc.fillColor("black");
    doc.y = 120;

    sectionTitle(doc, "Property Details");
    const y0 = doc.y;
    kv(doc, "Property #", "P-204", M, y0, 110);
    kv(doc, "Type", "Single Family Home", M + 120, y0, 140);
    kv(doc, "Tier", "Premium", M + 270, y0, 100);
    kv(doc, "Status", "Active", M + 380, y0, 100);
    const y1 = y0 + 36;
    kv(doc, "Bed / Bath", "4 BR / 3.5 BA", M, y1, 110);
    kv(doc, "Sq Ft", "3,420", M + 120, y1, 110);
    kv(doc, "Year Built", "2014", M + 240, y1, 110);
    kv(doc, "Pool / Spa", "Yes / Yes", M + 360, y1, 120);
    doc.y = y1 + 36;

    sectionTitle(doc, "Contacts");
    const cy = doc.y;
    kv(doc, "Owner", "Jane Owner · jane.owner@example.com · (239) 555-9988", M, cy, W - M * 2);
    kv(doc, "Property Manager", "Mike Rivera · mike@acmepm.com · (239) 555-3311", M, cy + 30, W - M * 2);
    kv(doc, "Emergency Contact", "Tom Owner (spouse) · (239) 555-7766", M, cy + 60, W - M * 2);
    doc.y = cy + 90;

    sectionTitle(doc, "Access & Security");
    const ay = doc.y;
    kv(doc, "Front Gate Code", "1980 #", M, ay, 110);
    kv(doc, "Garage Code", "8842", M + 120, ay, 110);
    kv(doc, "Alarm Code", "Stored — view in app", M + 240, ay, 200);
    kv(doc, "Lockbox", "Hidden under planter, code 4419", M, ay + 36, W - M * 2);
    doc.y = ay + 70;

    sectionTitle(doc, "Preferred Vendors");
    const vh = doc.y;
    doc.rect(M, vh, W - M * 2, 20).fillColor("#f5f3ff").fill();
    doc.fontSize(9).fillColor("#5b21b6");
    doc.text("Vendor", M + 8, vh + 6, { width: 180 });
    doc.text("Service", M + 200, vh + 6, { width: 130 });
    doc.text("Contact", M + 340, vh + 6, { width: 120 });
    doc.text("Rating", W - M - 50, vh + 6, { width: 42, align: "right" });
    doc.y = vh + 24;
    const vendors: Array<[string, string, string, string]> = [
      ["Coastal Pool Co.", "Pool service", "(239) 555-1010", "★★★★★"],
      ["GreenScape Lawn", "Landscaping", "(239) 555-2020", "★★★★☆"],
      ["RapidCool HVAC", "HVAC", "(239) 555-3030", "★★★★★"],
      ["Marco Plumbing", "Plumbing (emergency)", "(239) 555-4040", "★★★★☆"],
    ];
    doc.fontSize(9).fillColor("#0f172a");
    for (const [name, service, contact, rating] of vendors) {
      const y = doc.y;
      doc.text(name, M + 8, y, { width: 180 });
      doc.text(service, M + 200, y, { width: 130 });
      doc.text(contact, M + 340, y, { width: 120 });
      doc.fillColor("#ca8a04").text(rating, W - M - 50, y, { width: 42, align: "right" });
      doc.fillColor("#0f172a");
      doc.y = y + 14;
      doc.moveTo(M, doc.y).lineTo(W - M, doc.y).strokeColor("#f1f5f9").stroke();
      doc.moveDown(0.15);
    }

    sectionTitle(doc, "Recent Tasks (last 30 days)");
    const tasks: Array<[string, string, string]> = [
      ["Apr 28", "Weekly home watch", "Completed"],
      ["Apr 22", "Pool service", "Completed"],
      ["Apr 21", "Weekly home watch", "Completed"],
      ["Apr 14", "HVAC filter replacement", "Completed"],
      ["Apr 14", "Weekly home watch", "Completed"],
      ["Apr 07", "Weekly home watch", "Completed"],
    ];
    for (const [date, title, status] of tasks) {
      const y = doc.y;
      doc.fontSize(9).fillColor("#64748b").text(date, M, y, { width: 60 });
      doc.fillColor("#0f172a").text(title, M + 70, y, { width: 320 });
      doc.fillColor("#16a34a").text(status, W - M - 80, y, { width: 80, align: "right" });
      doc.y = y + 14;
    }

    doc.moveDown(0.4);
    sectionTitle(doc, "Upcoming Inspections");
    const ups: Array<[string, string, string]> = [
      ["May 02, 2026", "Monthly home watch", "Sarah Chen"],
      ["Jun 01, 2026", "Quarterly storm-prep inspection", "Mike Rivera"],
      ["Jul 01, 2026", "Monthly home watch", "Sarah Chen"],
    ];
    for (const [date, title, who] of ups) {
      const y = doc.y;
      doc.fontSize(9).fillColor("#7c3aed").text(date, M, y, { width: 100 });
      doc.fillColor("#0f172a").text(title, M + 110, y, { width: 280 });
      doc.fillColor("#475569").text(who, W - M - 120, y, { width: 120, align: "right" });
      doc.y = y + 14;
    }

    doc.moveDown(0.6);
    hr(doc);
    doc.fontSize(8).fillColor("#94a3b8").text(
      "Property report generated by Hubify. For the complete record including photos, warranties, purchasing links, and notes, view this property in the Hubify Console."
    );
  });
}
